version: 1.0.{build}
image: Windows
configuration: Debug
platform: x64
install:
- cmd: >-
    call olympus/buildmachine/install_dependencies.bat
clone_script:
- cmd: git clone --recursive https://github.com/SleepingSoul/olympus
build:
  project: olympus/olympus/olympus.sln
  parallel: true
  verbosity: normal